
main = ".open-next/worker.js"
name = "aquafornais"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[vars]
DATABASE_URL = "mysql://jeussval_admin:Admin@234@mx130.hostgator.mx/jeussval_aquadb"
BETTER_AUTH_SECRET = "NOSf9gzBoiF2Ea4sAzkxqNQWyqLWxogi"
BETTER_AUTH_URL = "https://aquafornais.dpdns.org/api/auth"
NEXT_PUBLIC_BETTER_AUTH_URL="https://aquafornais.dpdns.org/api/auth"
DISCORD_PUBLIC_KEY = "8e2b9726575ee3b1cba09587b61cfe91f4befa0af3643f48e2db15357261dd1e"
DISCORD_APP_ID = "1385332222839488665"
DISCORD_CLIENT_ID = "1385332222839488665"
DISCORD_CLIENT_SECRET = "SDTxOdk_jh81T5yMBQezVWzBJKp9VNJV"
STRIPE_SECRET_KEY = "sk_test_51RTP3NCVIHZJvQSKydSwCssH7GzrEkm7uHjgWqGmBtnGph34zHIhzQs8A9wUhC5mlowDp4WKxG6kVGDtGSGZIjpu00VtkkDAkV"
STRIPE_PUBLISHABLE_KEY = "pk_test_51RTP3NCVIHZJvQSK0jpvbOivvOOwkEmmnYszE4sg1CYkZvMgW85lRbLPPO5qU4WVS8fTUFBAaiFoif2UmdRkp92300WhHa7xpC"
NEXT_PUBLIC_APIKEY_FORTNITE = "d60d4e00-59f21374-a1c3d875-f9975241"
NEXTAUTH_SECRET = "NOSf9gzBoiF2Ea4sAzkxqNQWyqLWxogi"
NODE_ENV="development"