import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import {Providers} from '@/app/providers';
import {
  ClerkProvider, 
} from '@clerk/nextjs'
const SpaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
      <html lang="en" suppressHydrationWarning={true} data-theme="corporate" >
        <body
          className={`${SpaceGrotesk.variable}  antialiased`}
        >                    
            {children}          
        </body>
      </html>
      
    </ClerkProvider>
  );
}
